version: '3'

services: 
  
  mysql-dev:
    image: mysql:8.0.2
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes: 
      - "./sql-scripts:/docker-entrypoint-initdb.d"

  admin:
    image: adminer
    ports:
      - "8080:8080"

  tomcat:
    image: tomcat
    ports:
      - "8081:8080"
    volumes:
      - "./target/stockwatcher-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/stockwatcher.war"
